//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sky
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Context for the RIA application.
    /// </summary>
    /// <remarks>
    /// This context extends the base to make application services and types available
    /// for consumption from code and xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the WebContext class.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the context that is registered as a lifetime object with the current application.
        /// </summary>
        /// <exception cref="InvalidOperationException"> is thrown if there is no current application,
        /// no contexts have been added, or more than one context has been added.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
namespace Sky.Services
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// The DomainContext corresponding to the 'EchoRiaService' DomainService.
    /// </summary>
    public sealed partial class EchoRiaContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="EchoRiaContext"/> class.
        /// </summary>
        public EchoRiaContext() : 
                this(new WebDomainClient<IEchoRiaServiceContract>(new Uri("Sky-Services-EchoRiaService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="EchoRiaContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The EchoRiaService service URI.</param>
        public EchoRiaContext(Uri serviceUri) : 
                this(new WebDomainClient<IEchoRiaServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="EchoRiaContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public EchoRiaContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Asynchronously invokes the 'Echo' method of the DomainService.
        /// </summary>
        /// <param name="value">The value for the 'value' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<string> Echo(string value, Action<InvokeOperation<string>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("value", value);
            this.ValidateMethod("Echo", parameters);
            return ((InvokeOperation<string>)(this.InvokeOperation("Echo", typeof(string), parameters, true, callback, userState)));
        }
        
        /// <summary>
        /// Asynchronously invokes the 'Echo' method of the DomainService.
        /// </summary>
        /// <param name="value">The value for the 'value' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<string> Echo(string value)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("value", value);
            this.ValidateMethod("Echo", parameters);
            return ((InvokeOperation<string>)(this.InvokeOperation("Echo", typeof(string), parameters, true, null, null)));
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new EchoRiaContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'EchoRiaService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IEchoRiaServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'Echo' operation.
            /// </summary>
            /// <param name="value">The value for the 'value' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/EchoRiaService/EchoDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/EchoRiaService/Echo", ReplyAction="http://tempuri.org/EchoRiaService/EchoResponse")]
            IAsyncResult BeginEcho(string value, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginEcho'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginEcho'.</param>
            /// <returns>The 'String' returned from the 'Echo' operation.</returns>
            string EndEcho(IAsyncResult result);
        }
        
        internal sealed class EchoRiaContextEntityContainer : EntityContainer
        {
            
            public EchoRiaContextEntityContainer()
            {
            }
        }
    }
}
